In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [5]:
n = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]]
)

In [6]:
n

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [7]:
n[0,1] = 20

In [8]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [9]:
n

array([[ 1, 20,  3],
       [ 2,  3,  4],
       [ 3,  4,  5]])

In [10]:
n[2] = [10,20,30]

In [11]:
n

array([[ 1, 20,  3],
       [ 2,  3,  4],
       [10, 20, 30]])

In [12]:
n[:, 1]

array([20,  3, 20])

In [13]:
n[:, 1] = [1,2,3]

In [14]:
n

array([[ 1,  1,  3],
       [ 2,  2,  4],
       [10,  3, 30]])

In [15]:
np.random.rand(5,2)

array([[0.30279818, 0.40091446],
       [0.43790098, 0.51807188],
       [0.25110869, 0.13626712],
       [0.0073596 , 0.38662036],
       [0.15415685, 0.24171963]])

In [16]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [17]:
b = (10 + (a*2))**2 /100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [18]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

In [19]:
a >= 2

array([False, False,  True,  True,  True])

In [20]:
a > b

array([False, False,  True,  True,  True])

Retuns all the elements for which a is higher than b

In [21]:
a[a>b]

array([2, 3, 4])

# Multiplication

In [22]:
u = np.array([2, 4, 5, 6])

In [28]:
2* u

array([ 4,  8, 10, 12])

In [26]:
v = np.array([1,0,0,2])

In [27]:
u+v

array([3, 4, 5, 8])

In [29]:
u * v

array([ 2,  0,  0, 12])

In [41]:
def vector_vector_multiplication (u,v):
    #ensure that both vectors have the same dimension
    assert u.shape[0] == v.shape[0]
    
    # Setup initial values for the loop 
    n = u.shape[0]
    result = 0.0

    # Run the loop
    for i in range(n):
        result = result + u[i]*v[i]
    return result


In [42]:
a = vector_vector_multiplication(u,v)

In [43]:
type(a)

numpy.float64

In [39]:
b = u.dot(v)
b

np.int64(14)

In [45]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

In [46]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [53]:
U.shape[1]

4

In [54]:
def matrix_vector_multiplication (U,v):
    #ensure that both vectors have the same dimension
    assert U.shape[1] == v.shape[0]
    
    # Setup initial values for the loop 
    num_rows = U.shape[0]
    result = np.zeros(num_rows)

    # Run the loop for each row
    for i in range(num_rows):
        # Run the code to do a vector_vector multiplication using previous code
        result[i] = vector_vector_multiplication(U[i],v)
    return result


In [57]:
m = matrix_vector_multiplication (U,v)
m

array([14.,  5.,  5.])

In [58]:
V = np.array([
    [1,2,2],
    [0,0.5,1],
    [0,2,1],
    [2,1,0]
])

In [68]:
def matrix_matrix_multiplication (U,V):
    #ensure that both vectors have the same dimension
    assert U.shape[1] == V.shape[0]
    
    # Setup initial values for the loop 
    num_rows = U.shape[0]
    num_columns = V.shape[1]
    result = np.zeros((num_rows,num_columns))

    # Run the loop for each row
    for i in range(num_rows):
        Vi = V[:,i]
        # Run the code to do a vector_vector multiplication using previous code
        result[:,i] = matrix_vector_multiplication(U,Vi)
        
    return result


In [69]:
V[0,0]

np.float64(1.0)

In [70]:
matrix_matrix_multiplication (U,V)

array([[14. , 22. , 13. ],
       [ 5. ,  7. ,  5. ],
       [ 5. , 11.5,  9. ]])

In [71]:
U.dot(V)

array([[14. , 22. , 13. ],
       [ 5. ,  7. ,  5. ],
       [ 5. , 11.5,  9. ]])

# Identity Matrix

In [72]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# Inverse Matrix

In [77]:
# Create a Square matrix by taking the 3 first rows of the V matrix previously created
Vs = V [[0,1,2]]
Vs

array([[1. , 2. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [78]:
Vs1 = np.linalg.inv(Vs)
Vs1

array([[ 1.        , -1.33333333, -0.66666667],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [79]:
# Let's multiply Vs and it's inverser to see if we have the identity matrix
Vs.dot(Vs1)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])