In [77]:
import pandas as pd
import numpy as np

In [78]:
pd.__version__

'2.3.1'

In [79]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [80]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [81]:
df.index

RangeIndex(start=0, stop=9704, step=1)

In [82]:
df.fuel_type.describe()

count         9704
unique           2
top       Gasoline
freq          4898
Name: fuel_type, dtype: object

In [83]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [84]:
df.groupby('origin').fuel_efficiency_mpg.max()

origin
Asia      23.759123
Europe    25.967222
USA       24.971452
Name: fuel_efficiency_mpg, dtype: float64

Q6. Median value of horsepower

    Find the median value of horsepower column in the dataset.
    Next, calculate the most frequent value of the same horsepower column.
    Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
    Now, calculate the median value of horsepower once again.

Has it changed?

    Yes, it increased : Ye
    Yes, it decreased
    No


In [85]:
df.horsepower.mean()

np.float64(149.65729212983547)

In [86]:
df.horsepower.describe()

count    8996.000000
mean      149.657292
std        29.879555
min        37.000000
25%       130.000000
50%       149.000000
75%       170.000000
max       271.000000
Name: horsepower, dtype: float64

In [87]:
df.horsepower.value_counts()

horsepower
152.0    142
145.0    141
151.0    134
148.0    130
141.0    130
        ... 
40.0       1
57.0       1
245.0      1
252.0      1
61.0       1
Name: count, Length: 192, dtype: int64

In [88]:
df1 = df.fillna(value={'horsepower':152.0})

In [89]:
df1.horsepower.mean()

np.float64(149.82821516900248)

In [90]:
df.horsepower.mean()

np.float64(149.65729212983547)

Q7. Sum of weights

    Select all the cars from Asia
    Select only columns vehicle_weight and model_year
    Select the first 7 values
    Get the underlying NumPy array. Let's call it X.
    Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
    Invert XTX.
    Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
    Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
    What's the sum of all the elements of the result?

    Note: You just implemented linear regression. We'll talk about it in the next lesson.

    0.051
    0.51
    5.1
    51


In [91]:
# Create a subset of the total data frame by selecting the cars made in asia
df_asia = df[df['origin']=='Asia']
df_asia.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                   250            1.0       174.0     2714.219310   
12                  320            5.0       145.0     2783.868974   
14                  200            6.0       160.0     3582.687368   
20                  150            3.0       197.0     2231.808142   
21                  160            4.0       133.0     2659.431451   

    acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8           10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12          15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14          14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20          18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21           NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   

    fuel_efficiency_mpg  
8             16.823554  
12            16.175820  
14            11.871091  
20            18.889083  
21            16.077730

In [92]:
# Create a subset of of the ASIA data frame by keeping only the weight and the year
df_asia_sub = df_asia[['vehicle_weight', 'model_year']]

In [93]:
idx = np.arange(7)
idx


array([0, 1, 2, 3, 4, 5, 6])

In [94]:
# Create Matrix X by selecting the first 7 values of the subset of cars made in asia
X = df_asia_sub.iloc[idx].values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [95]:
# Transpose X using np method .transpose()
XT = np.transpose(X)
XT

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [96]:
# Compute XT . X
XTX= XT.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [97]:
# Let's invert XTX

XTX1 = np.linalg.inv(XTX)
XTX1

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [98]:
Test=XTX.dot(XTX1)
Test

array([[ 1.0000000e+00,  3.2292692e-15],
       [-8.6606366e-16,  1.0000000e+00]])

In [99]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [100]:
# XTX . XT

a = XTX1.dot(XT)

In [101]:
w = a.dot(y)
w

array([0.01386421, 0.5049067 ])

In [102]:
w.sum()

np.float64(0.5187709081074016)