In [1]:
import numpy as np

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [6]:
n = np.array([
    [1,2,3],
    [2,3,4],
    [3,4,5]]
)

In [7]:
n

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [8]:
n[0,1] = 20

In [21]:
np.linspace(1, 100, 10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [9]:
n

array([[ 1, 20,  3],
       [ 2,  3,  4],
       [ 3,  4,  5]])

In [10]:
n[2] = [10,20,30]

In [11]:
n

array([[ 1, 20,  3],
       [ 2,  3,  4],
       [10, 20, 30]])

In [22]:
n[:, 1]

array([20,  3, 20])

In [23]:
n[:, 1] = [1,2,3]

In [24]:
n

array([[ 1,  1,  3],
       [ 2,  2,  4],
       [10,  3, 30]])

In [26]:
np.random.rand(5,2)

array([[0.96268956, 0.91291486],
       [0.61641308, 0.54327926],
       [0.15868052, 0.37265716],
       [0.01097994, 0.4990956 ],
       [0.67173634, 0.70310549]])

In [28]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [29]:
b = (10 + (a*2))**2 /100
b

array([1.  , 1.44, 1.96, 2.56, 3.24])

In [30]:
a / b + 10

array([10.        , 10.69444444, 11.02040816, 11.171875  , 11.2345679 ])

In [31]:
a >= 2

array([False, False,  True,  True,  True])

In [32]:
a > b

array([False, False,  True,  True,  True])

Retuns all the elements for which a is higher than b

In [33]:
a[a>b]

array([2, 3, 4])

Multiplication